default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", 'db') %>
  username: <%= ENV.fetch("PGUSER", 'postgres') %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: bets_accounting_development

test:
  <<: *default
  database: bets_accounting_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: bets_accounting_production
