---
version: '2'
plugins:
  brakeman:
    enabled: true
    config:
      app_path: backend
  bundler-audit:
    enabled: true
    config:
      path: backend/Gemfile.lock
exclude_patterns:
  - "backend/db"
  - "**/node_modules/"
