image: "ruby:2.5"

stages:
  - test
  # - deploy

cache:
  paths:
    - vendor/ruby

variables:
  RAILS_ENV: test
  POSTGRES_DB: bets_accounting_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ''

before_script:
  - cp config/database-gitlab.yml config/database.yml
  - apt-get update -qq && apt-get install -yqq nodejs libpq-dev cmake
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --without development production --path vendor

rspec:
  stage: test
  services:
    - postgres:latest
  script:
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec

code_quality:
  stage: test
  script:
    - bundle exec pronto run -f gitlab -c origin/master
  only:
    - develop

updates:
  stage: test
  script:
    - bundle outdated --strict
  allow_failure: true

# deploy_production:
#   stage: deploy
#   environment: production
#   script:
#     - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#     # - gem install capistrano --no-ri --no-rdoc
#     - bundle exec cap production deploy
#   only:
#     - master
#   when: manual
