version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    env_file:
      - '.env'
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/usr/local/pgsql/data

  webpacker:
    build: .
    env_file:
      - '.env'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'

  app:
    env_file:
      - '.env'
    command: bundle exec puma -C config/puma.rb
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "8443:8443"
    depends_on:
      - db
      - webpacker
