# TODO: users for backend/frontend // fix rights

# Dont upgrade version to 3+
# > Version 3 no longer supports the condition form of depends_on.
# https://docs.docker.com/compose/compose-file/#depends_on
version: '2.4'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-11}-alpine
    ports:
      - "5432"
    tmpfs:
      - /tmp
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app:cached
      - rails_cache:/usr/src/app/tmp/cache
      - bundle:/bundle
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - EDITOR=vi
    command: bundle exec rails server -b 0.0.0.0 -p 8080
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
      - packs:/usr/src/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: yarn run serve
    ports:
      - "3333:8080"
    tmpfs:
      - /tmp

volumes:
  db-data:
  bundle:
  node_modules:
  rails_cache:
  packs:
