# TODO: users for backend/frontend // fix rights
version: '3.5'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-12}-alpine
    ports:
      - "15433:5432"
    tmpfs:
      - /tmp
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres_config.sql:/docker-entrypoint-initdb.d/postgres_config.sql
    restart: unless-stopped

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app:cached
      - rails_cache:/usr/src/app/tmp/cache
      - bundle:/bundle
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - EDITOR=vi
    command: sh -c "rm -f /usr/src/app/tmp/pids/server.pid ; bundle exec rails s -p 8080 -b 0.0.0.0"
    ports:
      - "8888:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp

  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
      - packs:/usr/src/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: yarn run serve
    ports:
      - "3333:8080"
    tmpfs:
      - /tmp

  waiter:
    build:
      context: waiter
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  db-data:
  bundle:
  node_modules:
  rails_cache:
  packs:
