# TODO: users for backend/frontend
# TODO: volumes for yarn and bundle
version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8888:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3333:8080"
