# Insert new cops alphabetically

inherit_gem:
  spicerack-styleguide:
    - rubocop.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/20190811211029_add_alpha_schemas.rb

Rails/InverseOf:
  Exclude:
    - app/models/bet.rb

Style/NumericLiterals:
  Exclude:
    - config/initializers/strong_migrations.rb

# has_key? and has_value? are more readable than key? and value?
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# You're gonna want a flak jacket for this one
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
