# Insert new cops alphabetically

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/**/*.rake"

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - '.pryrc'

# has_key? and has_value? are far more readable than key? and value?
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true
