# Insert new cops alphabetically

require:
  - standard/cop/semantic_blocks

inherit_gem:
  jetrockets-standard: config/rails.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

# has_key? and has_value? are more readable than key? and value?
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# You're gonna want a flak jacket for this one
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
