# Insert new cops alphabetically

inherit_gem:
  spicerack-styleguide:
    - rubocop.yml

# You're gonna want a flak jacket for this one
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
