# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(File.expand_path('.ruby-version', __dir__)).chomp

gem 'rails', '~> 6.0'

gem 'pg'
gem 'puma', '~> 4.0'

gem 'activerecord-import'
gem 'bcrypt'
gem 'blueprinter'
gem 'bootsnap', require: false
gem 'faker'
gem 'fast_blank', platform: :mri
gem 'knock', github: 'Mayurifag/knock'
gem 'oj'
gem 'rack-cors'

group :development, :test do
  gem 'awesome_rails_console', github: 'Mayurifag/awesome_rails_console',
                               branch: 'fix-parent-name-deprecation'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'hirb'
  gem 'hirb-unicode-steakknife', require: 'hirb-unicode'
  gem 'isolator'
  gem 'parallel_tests'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
end

group :development do
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'listen'
  gem 'ordinare', require: false
  gem 'rubocop'
  gem 'spicerack-styleguide'
  gem 'strong_migrations'
end

group :test do
  gem 'database_rewinder'
  gem 'factory_bot_rails'
  gem 'fuubar'
  # TODO: get rid of git when gem gonna be ready for rails 6+
  gem 'rspec-sqlimit', git: 'https://github.com/nepalez/rspec-sqlimit',
                       ref: '0c62feb61710c93f20f086a427a7a14784e5ca0d'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-console'
end

# TODO: not working on rails 6 or dip?
# gem 'regressor'
# gem 'factory_trace'
# gem 'database_consistency', require: false
