# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(File.expand_path('.ruby-version', __dir__)).chomp

gem 'rails', '>= 6.0.0'

gem 'pg', '>= 0.18', '< 2.0'
gem 'pg_search'
gem 'puma', '>= 4.1'

gem 'activerecord-import'
gem 'bcrypt'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'faker'
gem 'fast_blank'
gem 'jb'
gem 'knock'
gem 'rack-cors'

group :development, :test do
  gem 'awesome_rails_console', github: 'Mayurifag/awesome_rails_console',
                               branch: 'fix-parent-name-deprecation'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'hirb'
  gem 'hirb-unicode-steakknife', require: 'hirb-unicode'
  gem 'isolator'
  gem 'parallel_tests'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
end

group :development do
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'ordinare', require: false
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'strong_migrations'
end

group :test do
  gem 'database_rewinder'
  gem 'factory_bot_rails'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-console'
end
